# Comment
name: Team awesome's approval workflow
on: pull_request_review

jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest

    steps:
    - name: Label PR when approved
      run: pullreminders/label-when-approved-action
      env:
        APPROVALS: 1
        GITHUB_TOKEN: $GITHUB_TOKEN
        ADD_LABEL: Approved
